const translations = {
    ko: {
        "nav_home": "홈",
        "nav_services": "주요 사업",
        "nav_about": "회사 소개",
        "nav_contact": "오시는 길",
        "nav_issue": "히스토리 아카이브",
        "nav_algo": "알고리듬",
        "hero_title": "무한한 가능성을<br>연결합니다",
        "hero_desc": "IT 기술부터 공간 디자인, 미디어 콘텐츠까지.<br>유한회사 하이래빗이 당신의 비즈니스에 새로운 가치를 더합니다.",
        "hero_cta": "우리의 사업 보기",
        "services_title": "우리의 전문 분야",
        "badge_game": "신작 게임 출시! 🚀",
        "svc_software_title": "💻 소프트웨어 개발",
        "svc_software_desc": "비즈니스 효율을 극대화하는 맞춤형 웹/앱 솔루션과 혁신적인 프로그램을 개발합니다. <strong>(신작 모바일 게임 '뽕뽕비행기: 갤럭시 디펜더' 출시 완료!)</strong>",
        "svc_interior_title": "🎨 인테리어 디자인",
        "svc_interior_desc": "트렌디한 감각과 실용성을 바탕으로 영감을 주는 최적의 실내 공간을 디자인하고 시공합니다.",
        "svc_media_title": "🎬 미디어 콘텐츠",
        "svc_media_desc": "독창적인 기획력으로 감각적인 영상 및 미디어 콘텐츠를 창작하여 브랜드의 가치를 높입니다.",
        "svc_ecommerce_title": "🛒 E-커머스 & 컨설팅",
        "svc_ecommerce_desc": "전문적인 이커머스 운영과 경영 및 광고 설계 컨설팅을 통해 지속 가능한 성장을 돕습니다.",
        "about_subtitle": "ABOUT HIGH RABBIT",
        "about_title": "끊임없이 변화하며<br>새로운 가치를 창출합니다",
        "about_desc": "우리는 각 분야의 경계를 허물고 연결하여, 고객의 비즈니스에 전례 없는 가치와 시너지를 제공하는 것을 사명으로 삼고 있습니다.",
        "about_cta": "공식 캐릭터 보기",
        "stat_founded": "설립",
        "stat_services": "핵심 사업",
        "stat_possibilities": "가능성",
        "footer_company": "<strong>유한회사 하이래빗</strong> | 대표: 김효이",
        "footer_bizinfo": "설립일: 2026년 04월 10일 | 사업자등록번호: 170-81-04056",
        "copy_label_url": "홈페이지 주소 복사",
        "btn_copy": "주소 복사",
        "copy_label_share": "하이래빗 채널 및 공유",
        "share_issue": "히스토리 아카이브 유튜브",
        "share_algo": "알고리듬 유튜브",
        "share_algocafe": "알고리듬 카페 유튜브",
        "share_smart": "스마트 공유",
        "pg_title": "24시 AI 놀이터",
        "pg_software": "💻 소프트웨어",
        "pg_bb_title": "뿅뿅비행기",
        "pg_bb_desc1": "우주선을 조종해 외계 침공을 막아내는 꿀잼 아케이드 슈팅 게임!",
        "pg_bb_desc2": "지금 바로 구글 플레이스토어에서 정식 앱을 다운받아 즐겨보세요! (강력 추천)",
        "pg_btn_web": "웹 플레이",
        "pg_btn_app": "앱 다운로드",
        "pg_dream_title": "몽토끼 꿈풀이",
        "pg_dream_desc1": "간밤의 꿈이 궁금할 때? AI가 당신의 꿈을 완벽하게 해몽해 드립니다.",
        "pg_dream_desc2": "지금 바로 구글 플레이스토어에서 정식 앱을 다운받아 즐겨보세요! (강력 추천)",
        "pg_youtube": "📺 유튜브 채널",
        "pg_issue_title": "히스토리 아카이브",
        "pg_issue_desc1": "놓치기 쉬운 세상의 최신 트렌드와 알찬 필수 정보들을 한곳에.",
        "pg_issue_desc2": "지금 유튜브 채널 방문해서 바로 확인해 보세요!",
        "pg_btn_yt": "채널 방문",
        "pg_algo_title": "알고리듬",
        "pg_algo_desc1": "일할 때, 공부할 때, 쉴 때 듣기 좋은 하이래빗만의 프리미엄 BGM.",
        "pg_algo_desc2": "AI가 만든 놀라운 음악 지금 바로 들어보세요.",
        "pg_algo_desc3": "하루 종일 들어도 질리지 않는 중독성 있는 노래에 반하실 거예요!",
        "pg_algocafe_title": "알고리듬 카페",
        "pg_algocafe_desc1": "최고의 분위기를 선사하는 프리미엄 카페 음악 전문 유튜브 채널입니다.",
        "pg_algocafe_desc2": "지금 바로 방문해서 감미로운 카페 음악을 감상해 보세요!",
        "pg_vip_title": "🎵 하이래빗 프리미엄 음악",
        "pg_vip_desc": "나만의 특별한 음악 감상, 세상에 없던 음악 선물 앱",
        "pg_badge_vip": "오픈 준비 중",
        "shorts_badge": "👆 소리 켜기",
        "shorts_full": "전곡 듣기",
        "footer_analytics": "📊 구글 애널리틱스 대시보드",
        "footer_admin": "⚙️ 관리자 대시보드 (로컬)",
        "sw_hero_title": "미래를 설계하는 기술력",
        "sw_bb_desc1": "유한회사 하이래빗이 선보이는 첫 번째 모바일 게임 프로젝트입니다. 클래식한 슈팅 게임의 재미에 현대적인 감각과 화려한 그래픽을 더했습니다.",
        "sw_bb_desc2": "우주를 침공하는 외계 생명체로부터 은하계를 수호하세요. 하이래빗의 독자적인 게임 엔진 기술이 집약된 몰입감 넘치는 경험을 약속합니다.",
        "badge_review": "스토어 심사 중 (In Review)",
        "badge_web": "웹 버전 플레이 가능",
        "btn_web_run": "웹 버전 즉시 실행",
        "notice_audio_title": "🎵 웹 버전 배경음악 재생 안내",
        "notice_audio_1": "현재 웹 버전 게임은 최신 브라우저 정책으로 인해 배경음악이 제한될 수 있습니다.<br>",
        "notice_audio_2": "신나는 배경음악과 효과음이 포함된 <strong>완벽한 100% 플레이</strong>를 원하신다면, 구글 플레이스토어에서 <strong>정식 앱을 다운로드</strong>하여 즐겨주세요!",
        "sw_bb_feat1": "다양한 기체",
        "sw_bb_feat2": "업그레이드 시스템",
        "sw_bb_feat3": "강력한 보스전",
        "sw_dream_title": "몽토끼 꿈풀이 <br>(Global Dream App)",
        "sw_dream_desc1": "동양의 명리학적 상징과 서양의 심층 심리학(프로이트, 융) 이론을 결합한 10만 건 이상의 빅데이터 기반 프리미엄 해몽 솔루션입니다.",
        "sw_dream_desc2": "억눌린 무의식의 상징을 분석하고 현실의 스트레스를 해소하는 전문가 수준의 심리 분석 결과를 만나보세요.",
        "btn_web_connect": "웹 버전 즉시 접속",
        "sw_dream_feat1": "빅데이터 분석",
        "sw_dream_feat2": "심층 심리학",
        "sw_dream_feat3": "프리미엄 해석",
        "btn_back_home": "홈으로 돌아가기",
        "media_hero_title": "독창적인 미디어의 세계",
        "media_issue_title": "히스토리 아카이브",
        "media_issue_desc1": "세상의 복잡한 이슈를 명쾌하게 풀어내고, 꼭 알아야 할 상식을 재미있게 전달합니다. 유한회사 하이래빗이 야심차게 준비 중인 첫 번째 유튜브 프로젝트입니다.",
        "media_issue_desc2": "지적인 호기심을 채워줄 고품격 콘텐츠를 곧 만나보실 수 있습니다.",
        "btn_visit_yt": "유튜브 채널 방문하기",
        "media_algo_title": "알고리듬 (Algorhythm)",
        "media_algo_desc1": "바쁜 일상 속, 마음을 평온하게 채워주는 감성적인 로파이(Lo-Fi) 음악과 감각적인 힐링 비주얼 아트워크를 선보입니다. 하이래빗이 직접 작곡하고 합성한 고품질 BGM 메들리를 제공합니다.",
        "media_algo_desc2": "잔잔한 휴식과 집중이 필요할 때, 하이래빗의 음악 콘텐츠로 힐링해 보세요."

    },
    en: {
        "nav_home": "Home",
        "nav_services": "Services",
        "nav_about": "About Us",
        "nav_contact": "Location",
        "nav_issue": "History Archive",
        "nav_algo": "Algorhythm",
        "hero_title": "Connecting<br>Infinite Possibilities",
        "hero_desc": "From IT technology to spatial design and media content.<br>High Rabbit adds new value to your business.",
        "hero_cta": "View Our Services",
        "services_title": "Our Expertise",
        "badge_game": "New Game Released! 🚀",
        "svc_software_title": "💻 Software Development",
        "svc_software_desc": "We develop custom web/app solutions and innovative programs to maximize business efficiency. <strong>(New mobile game 'BongBong Airplane' released!)</strong>",
        "svc_interior_title": "🎨 Interior Design",
        "svc_interior_desc": "We design and construct optimal indoor spaces that inspire, based on trendy sense and practicality.",
        "svc_media_title": "🎬 Media Content",
        "svc_media_desc": "We increase brand value by creating sensuous video and media content with original planning.",
        "svc_ecommerce_title": "🛒 E-Commerce & Consulting",
        "svc_ecommerce_desc": "We help sustainable growth through professional e-commerce operations, management, and advertising design consulting.",
        "about_subtitle": "ABOUT HIGH RABBIT",
        "about_title": "Constantly evolving<br>to create new value",
        "about_desc": "Our mission is to break down boundaries and connect different fields to provide unprecedented value and synergy to our clients' businesses.",
        "about_cta": "View Official Character",
        "stat_founded": "Founded",
        "stat_services": "Core Services",
        "stat_possibilities": "Possibilities",
        "footer_company": "<strong>High Rabbit Ltd.</strong> | CEO: Hyo-i Kim",
        "footer_bizinfo": "Established: Apr 10, 2026 | Business Registration No: 170-81-04056",
        "copy_label_url": "Copy Website Address",
        "btn_copy": "Copy Address",
        "copy_label_share": "High Rabbit Channels & Share",
        "share_issue": "History Archive YouTube",
        "share_algo": "Algorhythm YouTube",
        "share_algocafe": "Algorhythm Cafe YouTube",
        "share_smart": "Smart Share",
        "pg_title": "24/7 AI Playground",
        "pg_software": "💻 Software",
        "pg_bb_title": "BbyongBbyong Airplane",
        "pg_bb_desc1": "A fun arcade shooting game where you pilot a spaceship to stop an alien invasion!",
        "pg_bb_desc2": "Download the official app from Google Play Store and enjoy! (Highly Recommended)",
        "pg_btn_web": "Web Play",
        "pg_btn_app": "App Download",
        "pg_dream_title": "MongRabbit Dream Interpretation",
        "pg_dream_desc1": "Curious about last night's dream? AI perfectly interprets your dream.",
        "pg_dream_desc2": "Download the official app from Google Play Store and enjoy! (Highly Recommended)",
        "pg_youtube": "📺 YouTube Channel",
        "pg_issue_title": "History Archive",
        "pg_issue_desc1": "The latest trends and essential information of the world in one place.",
        "pg_issue_desc2": "Visit the YouTube channel and check it out right now!",
        "pg_btn_yt": "Visit Channel",
        "pg_algo_title": "Algorhythm",
        "pg_algo_desc1": "High Rabbit's premium BGM for working, studying, and relaxing.",
        "pg_algo_desc2": "Listen to amazing AI-created music right now.",
        "pg_algo_desc3": "You will fall in love with addictive songs that you won't get tired of all day!",
        "pg_algocafe_title": "Algorhythm Cafe",
        "pg_algocafe_desc1": "A premium cafe music YouTube channel that provides the best atmosphere.",
        "pg_algocafe_desc2": "Visit the channel now and enjoy sweet cafe music!",
        "pg_vip_title": "🎵 High Rabbit Premium Music",
        "pg_vip_desc": "Special music appreciation just for you, a music gift app like no other",
        "pg_badge_vip": "Coming Soon",
        "shorts_badge": "👆 Unmute",
        "shorts_full": "Full Song",
        "footer_analytics": "📊 Google Analytics Dashboard",
        "footer_admin": "⚙️ Admin Dashboard (Local)",
        "sw_hero_title": "Technology designing the future",
        "sw_bb_desc1": "This is the first mobile game project presented by High Rabbit. We added a modern sense and gorgeous graphics to the fun of classic shooting games.",
        "sw_bb_desc2": "Defend the galaxy from alien life forms invading the universe. We promise an immersive experience integrating High Rabbit's original game engine technology.",
        "badge_review": "In Store Review",
        "badge_web": "Web Version Available",
        "btn_web_run": "Run Web Version Instantly",
        "notice_audio_title": "🎵 Web Version BGM Playback Notice",
        "notice_audio_1": "Currently, background music may be restricted in the web version game due to the latest browser policies.<br>",
        "notice_audio_2": "If you want a <strong>perfect 100% play</strong> with exciting background music and sound effects, please <strong>download the official app</strong> from the Google Play Store!",
        "sw_bb_feat1": "Various Aircraft",
        "sw_bb_feat2": "Upgrade System",
        "sw_bb_feat3": "Powerful Boss Battles",
        "sw_dream_title": "MongRabbit Dream Interpretation <br>(Global Dream App)",
        "sw_dream_desc1": "It is a premium dream interpretation solution based on over 100,000 big data combining Eastern Myeong리학 symbols and Western depth psychology (Freud, Jung) theories.",
        "sw_dream_desc2": "Meet expert-level psychological analysis results that analyze symbols of the repressed unconscious and relieve real-life stress.",
        "btn_web_connect": "Instant Web Connection",
        "sw_dream_feat1": "Big Data Analysis",
        "sw_dream_feat2": "Depth Psychology",
        "sw_dream_feat3": "Premium Interpretation",
        "btn_back_home": "Back to Home",
        "media_hero_title": "World of Original Media",
        "media_issue_title": "History Archive",
        "media_issue_desc1": "We clearly explain the world's complex issues and convey essential common sense in a fun way. It is the first YouTube project ambitiously prepared by High Rabbit.",
        "media_issue_desc2": "You will soon be able to meet high-quality content that will satisfy your intellectual curiosity.",
        "btn_visit_yt": "Visit YouTube Channel",
        "media_algo_title": "Algorhythm",
        "media_algo_desc1": "We present emotional Lo-Fi music and sensuous healing visual artwork that peacefully fill your mind in a busy daily life. High Rabbit provides high-quality BGM medleys composed and synthesized directly.",
        "media_algo_desc2": "When you need calm relaxation and concentration, heal with High Rabbit's music content."

    }
};

function changeLang(lang) {
    localStorage.setItem('hr_lang', lang);
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (translations[lang] && translations[lang][key]) {
            el.innerHTML = translations[lang][key];
        }
    });

    // Toggle button active state
    document.querySelectorAll('.lang-btn').forEach(btn => {
        btn.classList.remove('active');
        if(btn.getAttribute('data-lang') === lang) {
            btn.classList.add('active');
        }
    });
    
    document.documentElement.lang = lang;
}

// Initialize Language on DOM Load
document.addEventListener('DOMContentLoaded', () => {
    const savedLang = localStorage.getItem('hr_lang') || 'ko';
    changeLang(savedLang);
});
