export const DREAM_CATEGORIES = [
  { id: 'first_place', fileName: '1등 하는 꿈.jpg', key: 'first_place' },
  { id: 'family', fileName: '가족 만나는 꿈.jpg', key: 'family' },
  { id: 'beaten', fileName: '구타당하는 꿈.jpg', key: 'beaten' },
  { id: 'lost', fileName: '길 잃은 꿈.jpg', key: 'lost' },
  { id: 'falling', fileName: '높은곳에서 떨어지는 꿈.jpg', key: 'falling' },
  { id: 'chased', fileName: '도망치는 꿈.jpg', key: 'chased' },
  { id: 'money', fileName: '돈 줍는 꿈.jpg', key: 'money' },
  { id: 'poop', fileName: '똥싸는 꿈.jpg', key: 'poop' },
  { id: 'haircut', fileName: '머리카락 자르는 꿈.jpg', key: 'haircut' },
  { id: 'water', fileName: '물에 빠지는 꿈.jpg', key: 'water' },
  { id: 'snake', fileName: '뱀에 물리는 꿈.jpg', key: 'snake' },
  { id: 'lightning', fileName: '번개 맞는 꿈.jpg', key: 'lightning' },
  { id: 'naked', fileName: '벌거벗은 꿈.jpg', key: 'naked' },
  { id: 'flying', fileName: '비행하는 꿈.jpg', key: 'flying' },
  { id: 'gift', fileName: '선물 받는 꿈.jpg', key: 'gift' },
  { id: 'exam', fileName: '시험치는 꿈.jpg', key: 'exam' },
  { id: 'lost_shoes', fileName: '신발 잃어 버린 꿈.jpg', key: 'lost_shoes' },
  { id: 'crying', fileName: '울고있는 꿈.jpg', key: 'crying' },
  { id: 'celebrity', fileName: '유명인사 만나는 꿈.jpg', key: 'celebrity' },
  { id: 'eating', fileName: '음식 먹는 꿈.jpg', key: 'eating' },
  { id: 'teeth', fileName: '이 빠지는 꿈.jpg', key: 'teeth' },
  { id: 'breakup', fileName: '이별하는 꿈.jpg', key: 'breakup' },
  { id: 'pregnancy', fileName: '임신하는 꿈.jpg', key: 'pregnancy' },
  { id: 'car_crash', fileName: '자동차 사고 꿈.jpg', key: 'car_crash' },
  { id: 'ancestor', fileName: '조상님 만나는 꿈.jpg', key: 'ancestor' },
  { id: 'death', fileName: '죽는 꿈.jpg', key: 'death' },
  { id: 'earthquake', fileName: '지진나는 꿈.jpg', key: 'earthquake' },
  { id: 'house_fire', fileName: '집이 불타는 꿈.jpg', key: 'house_fire' },
  { id: 'big_tree', fileName: '큰 나무 꿈.jpg', key: 'big_tree' },
  { id: 'kiss', fileName: '키스하는 꿈.jpg', key: 'kiss' },
  { id: 'typhoon', fileName: '태풍부는 꿈.jpg', key: 'typhoon' },
  { id: 'makeup', fileName: '화장하는 꿈.jpg', key: 'makeup' }
];

export const FREUD_INTERPRETATIONS = {
  ko: {
    first_place: "💡 [핵심 상징: 1등, 우승]\n'1등'은 현실에서의 강한 성취욕, 사회적 인정 욕구, 그리고 경쟁에서의 승리를 상징합니다.\n\n📖 [상세 해몽]\n현재 진행 중인 프로젝트나 학업에서 당신의 능력을 온전히 발휘하고 싶은 잠재의식이 반영된 것입니다. 조만간 당신의 꾸준한 노력이 결실을 맺어 주변으로부터 큰 찬사를 받게 될 것을 암시하는 길몽입니다.",
    family: "💡 [핵심 상징: 가족]\n가족은 현재 당신의 '심리적 안정감', '소속감', 또는 반대로 '억압'을 반영하는 거울과 같습니다.\n\n📖 [상세 해몽]\n꿈에서 가족과 화목했다면 대인관계의 평안을, 갈등이 있었다면 현실의 책임감으로부터 독립하고 싶은 갈망을 의미합니다. 스스로의 내면을 돌아보고 진정한 휴식을 취할 때입니다.",
    beaten: "💡 [핵심 상징: 구타, 폭력]\n꿈에서의 폭력과 구타는 역설적으로 타인으로부터 받는 '강력한 관심', '비판적 조언', 또는 '예상치 못한 도움'을 상징합니다.\n\n📖 [상세 해몽]\n꿈에서의 고통은 현실에서의 긍정적인 자극이나 금전적 이득으로 전환되는 대길몽입니다. 조만간 누군가의 적극적인 지원을 받아 안고 있던 문제가 단번에 해결될 징조입니다.",
    lost: "💡 [핵심 상징: 미로, 길 잃음]\n길을 잃는 행위는 현재 직면한 진로에 대한 '불확실성', '인생의 과도기', '방황'을 상징합니다.\n\n📖 [상세 해몽]\n어느 방향으로 나아가야 할지 내면 깊은 곳에서 방황하고 있군요. 하지만 이는 새로운 가능성을 모색하기 위한 필수적인 혼란기이니, 조급해하지 말고 스스로의 직관을 믿으십시오.",
    falling: "💡 [핵심 상징: 추락]\n높은 곳에서의 추락은 '통제력 상실에 대한 원초적 두려움'과 '지위 하락'을 상징합니다.\n\n📖 [상세 해몽]\n현재 직장이나 인간관계에서 자신의 위치가 흔들릴까 불안해하고 있을 수 있습니다. 반면, 바닥에 닿기 전에 잠에서 깼다면 현재 겪고 있는 위기를 아슬아슬하게 극복해 낼 수 있음을 의미합니다.",
    chased: "💡 [핵심 상징: 추격자]\n누군가에게 쫓기는 것은 현실에서 회피하고 싶은 '압박감', '데드라인', '해결하지 못한 책임감'을 상징합니다.\n\n📖 [상세 해몽]\n쫓아오는 대상의 정체는 사실 당신 내면의 죄책감이나 심한 스트레스일 확률이 높습니다. 이제는 도망치지 말고 현실의 문제를 정면으로 마주하여 돌파해야 할 때입니다.",
    money: "💡 [핵심 상징: 돈]\n돈은 현실에서의 '권력', '에너지', '예상치 못한 행운' 또는 반대로 '애정의 결핍'을 상징합니다.\n\n📖 [상세 해몽]\n지폐 다발을 주웠다면 현실에서의 뜻밖의 횡재나 기회를 의미하지만, 동전 몇 닢을 주웠다면 오히려 인간관계에서의 외로움이나 사소한 근심거리가 생길 수 있음을 경고합니다.",
    poop: "💡 [핵심 상징: 대변(똥)]\n똥은 전통적으로 비료이자 풍요의 상징으로, '막대한 재물'과 '금전운'을 의미하는 최고의 매개체입니다.\n\n📖 [상세 해몽]\n내 몸에서 빠져나온 불순물이 거름이 되어 큰 결실을 맺는 이치입니다. 똥을 온몸에 뒤집어썼거나 그 양이 많을수록 조만간 큰 경제적 이득이 찾아오는 대길몽입니다.",
    haircut: "💡 [핵심 상징: 머리카락]\n머리카락은 당신의 '수명', '골칫거리', 또는 '자존심'을 상징합니다.\n\n📖 [상세 해몽]\n답답했던 머리를 깔끔하게 자르는 꿈은 오랫동안 골머리를 앓던 문제나 인간관계가 시원하게 정리됨을 의미하는 길몽입니다. 과거의 미련을 훌훌 털어버리고 새로운 마음가짐으로 출발하게 될 것입니다.",
    water: "💡 [핵심 상징: 물]\n물은 '무의식의 깊은 감정', '생명력', 그리고 '재물의 흐름'을 상징합니다.\n\n📖 [상세 해몽]\n맑은 물에 빠져 허우적대지 않고 편안함을 느꼈다면 큰 권력이나 재물의 흐름에 올라타게 될 대길몽입니다. 하지만 탁한 물이거나 두려움을 느꼈다면, 현재 감정적으로 감당하기 힘든 벅찬 상황에 직면해 있음을 암시합니다.",
    snake: "💡 [핵심 상징: 뱀]\n뱀은 '지혜', '강인한 생명력', '치유', 그리고 '은밀한 에너지'를 상징하는 영물입니다.\n\n📖 [상세 해몽]\n뱀에게 꽉 물리거나 독이 퍼지는 느낌을 받았다면, 조만간 당신의 인생에 큰 전환점이 될 귀인을 만나거나 전혀 예상치 못한 곳에서 재물운이 터질 것을 암시하는 아주 좋은 징조입니다.",
    lightning: "💡 [핵심 상징: 번개]\n벼락이나 번개는 하늘의 뜻이자 '갑작스러운 깨달음', '천운', '명성의 폭발'을 상징합니다.\n\n📖 [상세 해몽]\n맑은 하늘에 번개를 맞았다면, 당신의 이름이 세상에 널리 알려지고 부귀공명을 얻게 될 엄청난 대길몽입니다. 인생의 판도가 한순간에 뒤바뀔 강력한 행운이 다가오고 있습니다.",
    naked: "💡 [핵심 상징: 나체]\n벌거벗은 몸은 '무방비 상태의 취약함', '비밀 탄로의 두려움', '진실된 자아'를 상징합니다.\n\n📖 [상세 해몽]\n사회적 가면(페르소나)을 벗어던지고 온전한 자아로 인정받고 싶은 무의식적 욕구입니다. 남의 시선을 너무 의식하여 위축되어 있지 않은지 점검하고, 자신감을 가지시길 바랍니다.",
    flying: "💡 [핵심 상징: 비행]\n하늘을 자유롭게 나는 것은 일상적인 '속박과 억압으로부터의 완전한 해방'과 '높은 이상'을 상징합니다.\n\n📖 [상세 해몽]\n지상에 얽매이지 않고 원하는 곳으로 이동하는 당신의 모습은, 현재 추진 중인 일이나 목표가 아무런 장애물 없이 순조롭게 풀려나가 큰 성취를 이룰 것을 암시합니다.",
    gift: "💡 [핵심 상징: 선물]\n선물은 타인으로부터의 '인정', '애정', 혹은 '새로운 기회와 책임'을 상징합니다.\n\n📖 [상세 해몽]\n선물의 내용물보다 그것을 받을 때의 감정이 중요한데, 기뻤다면 현실에서도 귀인의 도움을 받아 좋은 소식을 듣게 될 것입니다. 누군가가 당신의 가치와 재능을 높게 평가하고 있다는 증거입니다.",
    exam: "💡 [핵심 상징: 시험]\n시험은 사회적 '평가', '압박감', '자기 검열'을 상징합니다.\n\n📖 [상세 해몽]\n당신이 현재 다른 사람의 평가나 사회적 기준에 극심한 스트레스를 받고 있음을 의미합니다. 완벽주의적인 성향 때문에 스스로를 너무 가혹하게 몰아세우고 있는 것은 아닌지 점검해 보세요. 준비는 이미 충분합니다.",
    lost_shoes: "💡 [핵심 상징: 신발]\n신발은 당신이 사회에서 서 있는 '위치', '직업', 또는 '의지하는 동반자'를 상징합니다.\n\n📖 [상세 해몽]\n신발을 잃어버리는 꿈은 현재의 직장, 연인, 혹은 친한 지인과의 관계에 금이 가거나 잠시 헤어질 수 있음을 경고합니다. 주변 사람들과의 관계나 자신의 멘탈을 세심하게 점검해 보십시오.",
    crying: "💡 [핵심 상징: 눈물]\n소리 내어 우는 것은 감정적 찌꺼기가 씻겨 나가는 '정화(Catharsis)'와 '스트레스 해소'를 상징합니다.\n\n📖 [상세 해몽]\n꿈속에서의 눈물은 현실의 기쁨과 웃음으로 치환됩니다. 오랫동안 당신을 짓누르던 근심 걱정과 불안이 모두 깨끗이 해결되고 홀가분하고 상쾌한 나날을 맞이하게 될 길몽입니다.",
    celebrity: "💡 [핵심 상징: 유명인]\n유명인사나 연예인은 당신 내면 깊은 곳에 자리한 '명예욕', '과시욕', 그리고 '강력한 귀인'을 상징합니다.\n\n📖 [상세 해몽]\n자신을 이끌어줄 멘토의 등장을 상징하기도 합니다. 조만간 당신의 숨겨진 능력을 세상에 알릴 아주 좋은 기회나, 기다리던 반가운 소식이 찾아올 것을 암시합니다.",
    eating: "💡 [핵심 상징: 음식]\n음식은 정신적, 육체적 '에너지'에 대한 강한 갈망과 '성취'를 상징합니다.\n\n📖 [상세 해몽]\n맛있고 풍성한 음식을 만족스럽게 먹었다면 현실에서도 일의 성과가 좋고 재물이 들어올 징조입니다. 하지만 음식을 먹고 체하거나 맛이 없었다면, 진행 중인 일에 무리가 따르고 있음을 의미합니다.",
    teeth: "💡 [핵심 상징: 치아]\n치아는 가족, 일가친척, 또는 조직 내에서의 '권력과 기반'을 상징합니다.\n\n📖 [상세 해몽]\n특히 윗니는 윗사람, 아랫니는 아랫사람을 의미하는데, 이빨이 빠지는 꿈은 주변 사람과의 이별이나 관계의 단절을 암시하는 흉몽으로 자주 해석됩니다. 한동안 주변 사람들의 안부와 건강을 각별히 챙기시길 권합니다.",
    breakup: "💡 [핵심 상징: 이별]\n이별은 '독립', '새로운 시작', 혹은 '역몽(반대로 이루어짐)'을 상징합니다.\n\n📖 [상세 해몽]\n연인이나 소중한 사람과 헤어지며 슬퍼했다면, 오히려 현실에서는 그 사람과의 유대감이 더욱 깊어지고 관계가 발전하게 될 것을 암시합니다. 잃고 싶지 않은 강한 애착이 불안으로 발현된 것입니다.",
    pregnancy: "💡 [핵심 상징: 임신]\n임신은 새로운 생명을 잉태하듯, '새로운 아이디어', '사업', '창조적 프로젝트'를 상징합니다.\n\n📖 [상세 해몽]\n현실에서 당신이 새로운 일을 구상하거나 시작하게 됨을 의미하는 대길몽입니다. 부른 배의 크기가 클수록 앞으로 맞이하게 될 성과나 재물의 크기가 방대할 것임을 의미하니 적극적으로 도전하세요.",
    car_crash: "💡 [핵심 상징: 자동차 사고]\n자동차 사고는 추진 중인 일의 '급격한 제동', '통제력 상실', '경고'를 상징합니다.\n\n📖 [상세 해몽]\n현재 당신이 추진하고 있는 일련의 과정에 무리가 따르고 있음에 대한 무의식의 강력한 경고입니다. 속도에 집착하여 중요한 것을 놓치고 있지 않은지, 일의 방향성을 잠시 멈춰 서서 재점검해야 합니다.",
    ancestor: "💡 [핵심 상징: 조상]\n돌아가신 조상님은 가문의 '수호령'이자 '중요한 메시지 전달자'를 상징합니다.\n\n📖 [상세 해몽]\n조상님의 표정이 밝았다면 집안에 경사가 생기고 모든 일이 순조롭게 풀릴 길몽이지만, 어둡고 근심 어린 표정이었다면 다가올 위험을 미리 경고하는 것이니 매사에 신중을 기해야 합니다.",
    death: "💡 [핵심 상징: 죽음]\n죽음은 언뜻 불길해 보이나, 꿈해몽에서는 '낡은 자아의 소멸'과 '완벽한 부활'을 상징합니다.\n\n📖 [상세 해몽]\n최고의 길몽 중 하나입니다. 과거의 실패나 콤플렉스는 모두 죽음과 함께 소멸되고, 현실에서는 새로운 인생의 막이 오르며 모든 일이 크게 융성하게 될 징조입니다.",
    earthquake: "💡 [핵심 상징: 지진]\n지진은 삶을 지탱하던 근본적인 기반(직업, 가정, 가치관)의 '급격한 변화'와 '붕괴'를 상징합니다.\n\n📖 [상세 해몽]\n위기가 닥칠 수 있음을 상징하지만, 무너진 잔해 위에서 살아남았다면 기존의 낡은 체제를 붕괴시키고 더욱 견고하고 훌륭한 새로운 인생을 성공적으로 재건하게 될 것임을 암시합니다.",
    house_fire: "💡 [핵심 상징: 불]\n불은 낡은 것의 '정화'와 새로운 생명력, 그리고 '폭발적인 운세의 상승'을 상징하는 강력한 매개체입니다.\n\n📖 [상세 해몽]\n자신의 집이 활활 타오르는 꿈은 모든 액운이 불에 타 사라지고, 완벽한 백지 상태가 됨을 의미합니다. 불길이 거셀수록 현실에서의 재물운과 사업운이 크게 융성하게 될 대길몽이니 기회를 잡으세요.",
    big_tree: "💡 [핵심 상징: 큰 나무]\n크고 울창한 나무는 '생명력', '건강', '든든한 기반', 그리고 '가문의 융성'을 상징합니다.\n\n📖 [상세 해몽]\n나무에 꽃이 피거나 튼실한 열매가 맺혀있었다면, 오랫동안 묵묵히 땀 흘려온 당신의 노력이 마침내 풍성한 결실을 맺어 막대한 부와 명예를 거머쥐게 될 것임을 의미합니다.",
    kiss: "💡 [핵심 상징: 키스]\n키스는 육체적인 욕구를 넘어, 특정 대상이나 정보와 하나로 '결합'하고 '깊이 이해'하려는 갈망을 상징합니다.\n\n📖 [상세 해몽]\n진행 중인 계약이 성공적으로 성사되거나, 상대방의 진심을 알아낼 수 있는 중요한 단서를 얻게 될 것입니다. 대인관계에서의 소통이 원활해짐을 뜻합니다.",
    typhoon: "💡 [핵심 상징: 태풍]\n거센 태풍은 외부의 통제할 수 없는 '거대한 힘', '사회적 압력', '시련'을 상징합니다.\n\n📖 [상세 해몽]\n주변의 환경 변화나 인간관계의 갈등으로 인해 큰 스트레스를 받고 있을 수 있습니다. 무리하게 맞서기보다는 잠시 몸을 낮추고 폭풍이 지나가길 기다리는 지혜와 휴식이 필요합니다.",
    makeup: "💡 [핵심 상징: 화장]\n얼굴에 화장을 하는 것은 진실을 감추고 매력적인 '페르소나(가면)'를 쓰고 싶어 하는 '방어기제'를 상징합니다.\n\n📖 [상세 해몽]\n스스로에 대한 콤플렉스를 극복하고 타인에게 돋보이고 싶은 마음이 강해져 있으니, 겉모습을 치장하기 이전에 내면의 자존감을 먼저 든든하게 돌보시길 바랍니다.",
    default: "💡 [핵심 상징: 무의식]\n이 꿈은 현실에서의 불안과 내면의 억압이 결합된 상징입니다.\n\n📖 [상세 해몽]\n깊은 무의식 속 소망이 상징적인 형태로 발현된 것입니다. 자신의 최근 감정 상태를 되돌아보세요."
  },
  en: {
    first_place: "💡 [Core Symbol: 1st Place, Winning]\n'First place' symbolizes a strong desire for achievement, social recognition, and victory in reality.\n\n📖 [Detailed Interpretation]\nThis reflects your subconscious urge to fully utilize your abilities in current projects. It is a highly positive dream suggesting your efforts will soon bear fruit.",
    family: "💡 [Core Symbol: Family]\nFamily acts as a mirror reflecting your psychological stability, sense of belonging, or feelings of suppression.\n\n📖 [Detailed Interpretation]\nHarmony implies peace in relationships, while conflict represents a desire for independence. It's time to reflect inwardly and seek true rest.",
    beaten: "💡 [Core Symbol: Being Beaten]\nParadoxically, violence in dreams symbolizes receiving strong attention, critical advice, or unexpected help.\n\n📖 [Detailed Interpretation]\nPain translates to positive stimulation or financial gain. A problem you've struggled with will soon be resolved with active support.",
    lost: "💡 [Core Symbol: Maze, Being Lost]\nWandering symbolizes current uncertainties about your career, a transitional phase, and aimlessness.\n\n📖 [Detailed Interpretation]\nYou are confused about your direction. However, this is a necessary period to explore new possibilities, so trust your intuition.",
    falling: "💡 [Core Symbol: Falling]\nFalling from a height represents a primal fear of losing control and a drop in status.\n\n📖 [Detailed Interpretation]\nYou may be anxious about your position shaking at work. Waking up before hitting the ground means you will narrowly overcome the crisis.",
    chased: "💡 [Core Symbol: Pursuer]\nBeing chased symbolizes pressure you want to escape, deadlines, and unfulfilled responsibilities.\n\n📖 [Detailed Interpretation]\nThe pursuer is likely your own guilt or stress. Stop running and face the real-world problems head-on.",
    money: "💡 [Core Symbol: Money]\nMoney symbolizes power, energy, unexpected luck, or conversely, a lack of affection.\n\n📖 [Detailed Interpretation]\nFinding bills signifies a windfall, whereas finding coins warns of potential loneliness or minor worries.",
    poop: "💡 [Core Symbol: Feces]\nFeces is traditionally a symbol of fertilizer and abundance, representing massive wealth.\n\n📖 [Detailed Interpretation]\nImpurities expelled become manure yielding great results. The more you are covered, the greater the economic gain.",
    haircut: "💡 [Core Symbol: Hair]\nHair symbolizes your lifespan, worries, or pride.\n\n📖 [Detailed Interpretation]\nCutting hair neatly is a positive dream meaning a long-standing headache will be resolved. You will brush off past regrets.",
    water: "💡 [Core Symbol: Water]\nWater symbolizes deep unconscious emotions, vitality, and the flow of wealth.\n\n📖 [Detailed Interpretation]\nComfort in clear water means riding a wave of wealth. Murky water or fear implies facing an emotionally overwhelming situation.",
    snake: "💡 [Core Symbol: Snake]\nA snake symbolizes wisdom, strong vitality, healing, and secret energy.\n\n📖 [Detailed Interpretation]\nBeing bitten suggests meeting a benefactor who will be a major turning point, or financial luck bursting from an unexpected place.",
    lightning: "💡 [Core Symbol: Lightning]\nLightning symbolizes the will of the heavens, sudden enlightenment, and divine luck.\n\n📖 [Detailed Interpretation]\nBeing struck under a clear sky signifies your name becoming widely known, bringing great wealth and honor.",
    naked: "💡 [Core Symbol: Nakedness]\nBeing naked symbolizes vulnerability, fear of exposed secrets, and the true self.\n\n📖 [Detailed Interpretation]\nIt reflects an unconscious desire to throw off your social mask and be accepted. Don't be too conscious of others' gaze.",
    flying: "💡 [Core Symbol: Flying]\nFlying freely signifies complete liberation from daily constraints and high ideals.\n\n📖 [Detailed Interpretation]\nMoving unanchored implies that the work you are pursuing will progress smoothly without obstacles.",
    gift: "💡 [Core Symbol: Gift]\nA gift symbolizes recognition, affection, or new opportunities and responsibilities.\n\n📖 [Detailed Interpretation]\nIf you felt happy, you will soon hear good news with a benefactor's help. Someone highly values your worth.",
    exam: "💡 [Core Symbol: Exam]\nTaking an exam symbolizes social evaluation, pressure, and self-censorship.\n\n📖 [Detailed Interpretation]\nYou are under extreme pressure from others' standards. Check if you are driving yourself too harshly.",
    lost_shoes: "💡 [Core Symbol: Shoes]\nShoes symbolize your position in society, job, or a partner you rely on.\n\n📖 [Detailed Interpretation]\nLosing shoes warns of a potential crack in relationships with your job or lover. Carefully re-evaluate your surroundings.",
    crying: "💡 [Core Symbol: Tears]\nCrying out loud symbolizes catharsis and stress relief.\n\n📖 [Detailed Interpretation]\nTears in a dream are replaced by joy in reality. Worries weighing you down will be resolved.",
    celebrity: "💡 [Core Symbol: Celebrity]\nA celebrity symbolizes a deep-seated desire for fame and the appearance of a powerful mentor.\n\n📖 [Detailed Interpretation]\nIt suggests a great opportunity or welcome news will soon arrive to let the world know of your abilities.",
    eating: "💡 [Core Symbol: Food]\nFood symbolizes a strong craving for mental and physical energy and achievement.\n\n📖 [Detailed Interpretation]\nEating deliciously is a sign of good performance and wealth. Indigestion means an unreasonable strain on your work.",
    teeth: "💡 [Core Symbol: Teeth]\nTeeth symbolize family, relatives, or power within an organization.\n\n📖 [Detailed Interpretation]\nLosing teeth is an ominous sign hinting at separation or severing of relationships. Check on the health of close ones.",
    breakup: "💡 [Core Symbol: Breakup]\nA breakup symbolizes independence, a new beginning, or is a 'reverse dream'.\n\n📖 [Detailed Interpretation]\nCrying out of sadness ironically suggests your bond will deepen. It is a manifestation of strong attachment.",
    pregnancy: "💡 [Core Symbol: Pregnancy]\nPregnancy symbolizes conceiving a new idea, business, or creative project.\n\n📖 [Detailed Interpretation]\nThe larger the belly, the more immense the achievement or wealth you will face. Take on challenges proactively.",
    car_crash: "💡 [Core Symbol: Car Crash]\nA car crash symbolizes a sudden brake on your endeavors, loss of control, and a warning.\n\n📖 [Detailed Interpretation]\nIt's a powerful warning that your current process faces strain. Pause and re-examine your direction.",
    ancestor: "💡 [Core Symbol: Ancestor]\nA deceased ancestor symbolizes a guardian spirit and an important messenger.\n\n📖 [Detailed Interpretation]\nA bright expression predicts joyful family events. A dark expression is a warning of impending danger.",
    death: "💡 [Core Symbol: Death]\nDeath symbolizes the annihilation of the old self and perfect resurrection.\n\n📖 [Detailed Interpretation]\nPast failures perish with death, and a new chapter of life opens, signifying all affairs will prosper greatly.",
    earthquake: "💡 [Core Symbol: Earthquake]\nAn earthquake symbolizes a sudden change and collapse of your life's foundations.\n\n📖 [Detailed Interpretation]\nSurviving the ruins implies you will dismantle the obsolete system and rebuild a stronger, magnificent new life.",
    house_fire: "💡 [Core Symbol: Fire]\nFire symbolizes purification, vitality, and an explosive rise in fortune.\n\n📖 [Detailed Interpretation]\nYour house blazing means misfortune burns away, leaving a blank slate. The fiercer the flames, the greater your luck.",
    big_tree: "💡 [Core Symbol: Big Tree]\nA large tree symbolizes vitality, health, solid foundations, and family prosperity.\n\n📖 [Detailed Interpretation]\nBlooming flowers or fruits signify your sweat-drenched efforts will bear abundant fruit, bringing massive wealth.",
    kiss: "💡 [Core Symbol: Kiss]\nA kiss symbolizes a strong craving to unite and deeply understand a specific object or person.\n\n📖 [Detailed Interpretation]\nAn ongoing contract may be finalized, or you will obtain a crucial clue to decipher someone's true intentions.",
    typhoon: "💡 [Core Symbol: Typhoon]\nA typhoon symbolizes an uncontrollable external force, social pressure, and hardship.\n\n📖 [Detailed Interpretation]\nYou may be suffering immense stress. Rather than fighting forcefully, lay low and wait for the storm to pass.",
    makeup: "💡 [Core Symbol: Makeup]\nMakeup symbolizes a defense mechanism, hiding your true self behind an attractive persona.\n\n📖 [Detailed Interpretation]\nYour desire to overcome complexes has grown strong. Take care of your inner self-esteem first.",
    default: "💡 [Core Symbol: Unconscious]\nThis dream symbolizes a combination of real-world anxiety and inner suppression.\n\n📖 [Detailed Interpretation]\nA deep unconscious desire has manifested. Reflect on your recent emotional state."
  }
};
